Package version bump for recently merged changes (v2.3.0)
LabKey/labkey-api-r pull request #31
Opened 2019-05-24 13:41 UTC by cnathe

- note that the package built and checked in to svn trunk already has these updates

2019-05-24 16:47 UTC, labkey-tchad approved these changes

2019-05-24 17:11 UTC, labkey-tchad requested changes
Actually. Do we want to remove `webDavTest.R` since it requires a very specific local setup?

2019-05-25 03:19 UTC, cnathe commented
Good call @labkey-tchad. I removed that file.

2019-05-28 15:20 UTC, labkey-tchad approved these changes

2019-05-28 15:39 UTC, merged