7368: Conditional Formats of Fields
LabKey/labkey-api-r pull request #50
Opened 2020-06-09 17:56 UTC by RosalineP

#### Rationale
We're including functionality on our R API to allow conditional format definitions on fields to be created, removed, and updated, for functionality parity with our Python and JS APIs.

#### Related Pull Requests
* https://github.com/LabKey/labkey-api-python/pull/34

#### Changes
* labkey.domain.conditionalFormat: Create a conditional format data frame.
* labkey.domain.queryFilter: Helper for creating a query filter string.
* labkey.domain.queryFilterEnum: Return a list specifying permitted validator comparators.
* Documentation updates

2020-06-09 17:57 UTC, RosalineP commented on Rlabkey/R/labkey.domain.R
> +        HAS_ANY_VALUE = '',
This casing was taken directly from the python api. Perhaps we want a different casing in R?

2020-06-10 20:18 UTC, cnathe requested changes
Overall this looks good. I just have some comments / suggestions about the function names, etc. Let me know if you'd like to discuss via a call.

2020-06-10 20:18 UTC, cnathe commented on Rlabkey/R/labkey.domain.R
> +labkey.domain.conditionalFormat <- function(queryFilter, bold=FALSE, italic=FALSE, strikeThrough=FALSE, textColor="", backgroundColor="")
do we want to include the action verb in the function name here at all? i.e. `labkey.domain.createConditionalFormat()`

2020-06-10 20:18 UTC, cnathe commented on Rlabkey/R/labkey.domain.R
> +labkey.domain.conditionalFormat <- function(queryFilter, bold=FALSE, italic=FALSE, strikeThrough=FALSE, textColor="", backgroundColor="")
Also, should the defaults for the textColor and backgroundColor params be empty strings or `NULL`? Maybe the current empty string is expected on the server side, just wanted to check.

2020-06-10 20:18 UTC, cnathe commented on Rlabkey/R/labkey.domain.R
> +labkey.domain.queryFilterEnum <- function()
instead of a function here, I wonder if this could be defined as a global variable, see example in labkey.experiment.R for `labkey.experiment.SAMPLE_DERIVATION_PROTOCOL`. That example is just a string, but I think we might be able to do the same thing here. If that works, I'd probably call it something like `labkey.query.FILTER_TYPES`

Also, it seems like this mapping already exists or is duplicated in the makeFilter.R file, I wonder if there would be a way to share this definition with that use case (that can be for another PR in the future).

2020-06-10 20:18 UTC, cnathe commented on Rlabkey/R/labkey.domain.R
> +        HAS_ANY_VALUE = '',
That all caps casing with the underscores is what I would expect.

2020-06-10 20:18 UTC, cnathe commented on Rlabkey/R/labkey.domain.R
> +labkey.domain.queryFilter <- function(value, filterType, additionalValue=NULL, additionalFilter=NULL)
Similar to comment above, should this include a verb? i.e. `labkey.domain.createQueryFilter`

2020-06-10 20:18 UTC, cnathe commented on Rlabkey/R/labkey.domain.R
> +labkey.domain.queryFilter <- function(value, filterType, additionalValue=NULL, additionalFilter=NULL)
Also, since this is specific to a query filter for conditional formats, I'd name it something like `labkey.domain.createConditionalFormatQueryFilter()`.

2020-06-10 20:18 UTC, cnathe commented on Rlabkey/man/labkey.domain.queryFilter.Rd
> +labkey.domain.queryFilter(value, filterType, additionalValue=NULL, additionalFilter=NULL)
I didn't note this in the R source code file, but I usually think of the operator coming first and then the value. I might suggest switching the order of those params.

2020-06-10 20:18 UTC, cnathe commented on Rlabkey/man/labkey.domain.queryFilter.Rd
> +This function can be used to as a convenience wrapper to construct a query filter. Two relational expressions may be
As mentioned in the R source code for this, isn't this method specialized for the conditional format case because of the "format.column" prefix that it adds? If so, I'd add that to this description about what it can be used for. The rest of the description here about the handling of the params is great!

2020-06-10 20:18 UTC, cnathe commented on Rlabkey/man/labkey.domain.conditionalFormat.Rd
> +If text formatting options are not specified, the default displayed as black text on a white background.
```suggestion
If text formatting options are not specified, the default is to display the value as black text on a white background.
```

2020-06-10 20:18 UTC, cnathe commented on Rlabkey/man/labkey.domain.conditionalFormat.Rd
> +domain$fields$conditionalFormats[[3]] = rbind(cf1,cf2)
nice example!

2020-06-10 22:54 UTC, RosalineP commented on Rlabkey/R/labkey.domain.R
> +labkey.domain.queryFilterEnum <- function()
I like this global variable approach better! Thanks for the suggestion :)

2020-06-11 17:45 UTC, RosalineP commented on Rlabkey/R/labkey.domain.R
> +labkey.domain.conditionalFormat <- function(queryFilter, bold=FALSE, italic=FALSE, strikeThrough=FALSE, textColor="", backgroundColor="")
I get a 'arguments imply differing number of rows' error when I make the default NULL instead of an empty string on those params, unfortunately.

2020-06-12 13:23 UTC, cnathe approved these changes

2020-06-12 13:23 UTC, cnathe commented on Rlabkey/man/labkey.domain.FILTER_TYPES.Rd
> +This function can be used to return a list specifying the set of permitted validator operators, using names to map
```suggestion
This constant contains a list specifying the set of permitted validator operators, using names to map
```

2020-06-16 17:16 UTC, merged